# Generated by Django 4.0.3 on 2022-04-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_basemodel_college_course_faculty_marksheet_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roll_Id',
            new_name='role_Id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='roll_Name',
            new_name='role_Name',
        ),
    ]
